language: node_js

services:
    - docker

before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
    - docker build -t "$REPO:latest" .
    - docker push "$REPO:latest"

after_script:
    - docker logout
